### ISSUE TITLE
Gracefully handle remote docker errors

### ISSUE THREAD

**Issue by slack** [deis/controller#556] opened 2016-03-23 20:16 UTC
When doing a `deis pull` without proper permissions results in a 500 rather than a useful error. From controller logs:
```
docker.errors.DockerException: b'{"errorDetail":{"code":403,"message":"Error: Status 403 trying to pull repository jhansen/xxx: \\"{\\\\\\"error\\\\\\": \\\\\\"Permission Denied\\\\\\"}\\""},"error":"Error: Status 403 trying to pull repository jhansen/xxx: \\"{\\\\\\"error\\\\\\": \\\\\\"Permission Denied\\\\\\"}\\""}\r\n'
```

Should handle gracefully and return a good error message.

**Comment by helgi** [comment] 2016-03-23 20:17
Duplicate of #545 - You can keep this open if you like and close the other

**Comment by helgi** [comment] 2016-04-09 17:09
Do we want to surface up a general "Something went wrong with a Docker operation, here are the raw details" or try to get details?

For all the various docker errors we will have to reach into the json blob that is returned during the stream and figure out what each means to give a meaningful error. Should not be very complicated, more afraid of the plethora of error types. Maybe catching the most critical ones like "permission denied", "timeout" and so on would be enough?

**Comment by slack** [comment] 2016-04-09 17:14
Where we can, we should strive to provide as much actionable information as possible.

If we want to clean up known and common errors, that's great. For unexpected stuff, I'd be fine with passing through the contents of "code", "message" or "error", even if they aren't pretty.

**Comment by helgi** [comment] 2016-04-09 17:17
So at least tease out `code`, `message` or `error` (or a combination there off), that should be pretty doable.

Bumping us to docker-py 1.8.0 right now that gives us some more insights on what's up in general.

**Closed** 2016-04-11 23:05 UTC
Labels: in progress
