### ISSUE TITLE
'deis pull' not using Procfile, causes 404 and 503 errors when using deis ps:scale 

### ISSUE THREAD

**Issue by seanknox** [deis/controller#1058] opened 2016-09-12 22:40 UTC
@helgi @kmala following up from our earlier conversation: 

`Procfile` doesn't seemed to be considered when deploying an app image via `deis pull`. This is on v2.4.0.

STR:
1. `deis create odoyle-rules`
1. `deis config:set BUNCH_OF_ENV_VARS ... -a  odoyle-rules`
1. `deis registry:set username=... password=... -a  odoyle-rules`
1. `deis pull quay.io/... -a  odoyle-rules`
1. odoyle-rules.example.com works at this point and is running a single `cmd` process.
1. Attempting to scale processes to match `Procfile` in the project yields a 404 error: `deis ps:scale cmd=0 web=1 worker=1` 
```
$ deis ps:scale cmd=0 web=1 worker=1 -a odoyle-rules                                                           
Scaling processes... but first, coffee!
Error: Not Found

## controller
[2016-09-12T22:23:53+00:00] - deis/deis-controller - 172.20.75.70 - - - 404 - "POST /v2/apps/odoyle-rules/scale/ HTTP/1.1" - 522 - "-" - "Deis Client vv2.4.0" - "~^deis\x5C.(?<domain>.+)$" - 100.66.35.56:80 - deis.example.com - 0.272 - 0.366
```
1. Using a `git push odoyle-rules master` deploy fixes the 404 and allows `deis ps:scale` work: 
```
$ deis ps:scale web=1 worker=1 -a odoyle-rules                                                                    
Scaling processes... but first, coffee!
done in 31s
=== odoyle-rules Processes
--- web:
odoyle-rules-web-3986992675-t34p4 up (v6)
--- worker:
odoyle-rules-worker-4178919286-eex5b up (v6)
```
However the router is set to permanently return a 503:
```
    server {
        listen 8080;
        server_name ~^odoyle-rules\.(?<domain>.+)$;
        server_name_in_redirect off;
        port_in_redirect off;
        set $app_name "odoyle-rules";

        
        listen 6443 ssl http2 ;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS;
        ssl_prefer_server_ciphers on;
        ssl_certificate /opt/router/ssl/odoyle-rules.crt;
        ssl_certificate_key /opt/router/ssl/odoyle-rules.key;
        
        ssl_session_tickets on;
        ssl_buffer_size 4k;
        ssl_dhparam /opt/router/ssl/dhparam.pem;
        

        

        vhost_traffic_status_filter_by_set_key odoyle-rules application::*;

        location / {
            return 503;
        }
        
    }
```

**Comment by bacongobbler** [comment] 2016-09-12 23:08
I believe this is a duplicate of another issue @aledbf opened a while ago before we were GA with 2.0. I'm on mobile atm but I'll see if I can find it at home

**Closed** 2016-09-13 01:49 UTC
Labels: bug, in progress, priority 1
