### ISSUE TITLE
Unable to config:set PORT for an application which has had a failed deploy due to PORT being missing

### ISSUE THREAD

**Issue by robholland** [deis/controller#1093] opened 2016-09-29 11:29 UTC
We converted our cluster over to using an external registry by adjusting manifests, uninstall + install. When trying to deploy an app that was previously deployed from the in-cluster registry with the cluster configuration now swung over the external registry I got an error about PORT being missing:

```
Successfully built d84e715fcee4
Pushing to registry
Build complete.
Launching App...
remote: 2016/09/29 11:08:04 Error running git receive hook [publishing release (Unknown Error (400): {"detail":"PORT needs to be set in the config when using a private registry"})]
```

Unfortunately I can't set PORT now:

```
$ deis config:set PORT=5000
Creating config... Error: Unknown Error (400): {"detail":"(app::deploy): PORT needs to be set in the config when using a private registry"}
```

**Comment by robholland** [comment] 2016-09-29 11:30
Hmm. As an update to this, re-running the command succeeded. So... I don't know if this is an issue or not!

**Comment by bacongobbler** [comment] 2016-09-29 15:11
@robholland which version of workflow are you running?

**Comment by robholland** [comment] 2016-09-29 15:14
2.6.0.

**Comment by bacongobbler** [comment] 2016-09-29 15:18
Interesting. I guess we can close this for now unless you have a way to reliably reproduce this issue. If you have any controller logs that might be helpful in this case :)

**Comment by robholland** [comment] 2016-09-29 15:21
It happened for every one of our apps, the first deploy after adjusting the cluster registry it complains, first config:set fails, second succeeds.  

--  
Rob Holland

**Comment by bacongobbler** [comment] 2016-09-29 15:26
> the first deploy after adjusting the cluster registry

So you originally deployed using the in-cluster registry, then switched to an off-cluster registry after that? If you can write down how you set that up, that would be very helpful when trying to test. Just trying to grab the details down so we can try to reproduce.

Controller logs would also be helpful here. :)

**Comment by robholland** [comment] 2016-09-29 19:51
So originally we built the cluster using the in-cluster docker registry and deployed our applications. Later we started using a shared base image for our applications al la quay.io/deis/base, however deis wasn't able deploy the updates apps as it couldn't pull the base image as it was in a private repo. So I adjusted our generate_params template to switch us to off-cluster docker registry using our private quay.io account rather than the in-cluster one, then did the helmc generate + uninstall + install dance to get those changes applied.

When attempting to deploy any of the applications using the shared base layer again (having also replaced dockerbuilder with my custom one from https://github.com/deis/dockerbuilder/pull/101) we got the error mentioned above ^^

Running config:set PORT twice for each app fixed the issue :)

**Comment by bacongobbler** [comment] 2016-09-29 20:27
Sounds good. Unfortunately looking at the logs you provided to me over email didn't indicate anything obvious that we or you are doing wrong. I'm going to close this as fixed for now since I did test this and it worked for me. I wonder if it has to do with a connection error to the private repo?

Either way let's close this until we can get a reliable reproduction case. Thanks for the bug report!

**Closed by bacongobbler** 2016-09-29 20:27 UTC
