### ISSUE TITLE
It is possible to add 2 keys with different contents

### ISSUE THREAD

**Issue by jchauncey** [deis/controller#679] opened 2016-04-27 22:32 UTC
```
╰─± deis keys:add
Found the following SSH public keys:
1) deis-champagne.pub jonathanchauncey@ENG000637.local
2) deis.pub deis
3) id_boot2docker.pub jonathanchauncey@ENG000637.local
4) id_rsa.pub jonathanchauncey@ENG000637.local
0) Enter path to pubfile (or use keys:add <key_path>)
Which would you like to use with Deis? 1
Uploading deis-champagne.pub to deis... done
╭─jonathanchauncey at ENG000637 in ~/go/src/github.com/deis/k8s-claimer on master✔ using ‹2.0.0-p645›
╰─± deis keys:add
Found the following SSH public keys:
1) deis-champagne.pub jonathanchauncey@ENG000637.local
2) deis.pub deis
3) id_boot2docker.pub jonathanchauncey@ENG000637.local
4) id_rsa.pub jonathanchauncey@ENG000637.local
0) Enter path to pubfile (or use keys:add <key_path>)
Which would you like to use with Deis? 3
Uploading id_boot2docker.pub to deis... done
╭─jonathanchauncey at ENG000637 in ~/go/src/github.com/deis/k8s-claimer on master✔ using ‹2.0.0-p645›
╰─± deis keys:list
=== admin Keys
jonathanchauncey@ENG000637.local ssh-rsa AAAAB3Nz...0637.local
jonathanchauncey@ENG000637.local ssh-rsa AAAAB3Nz...0637.local
```

**Comment by bacongobbler** [comment] 2016-05-19 18:20
this looks important enough to fix for the release candidate.

**Comment by slack** [comment] 2016-06-02 22:34
A bit confused on this one, is it that you expect a 1:1 between user and key?

A user with multiple ssh keys is fine. But a key should not be shared between multiple users.

**Comment by bacongobbler** [comment] 2016-06-03 01:29
I think it's just the confusion that the client shows the pulley and the comment, whereas it's the fingerprint that uniquely identifies the key now. Probably just a client fix.

**Comment by mboersma** [comment] 2016-08-23 20:28
Let's move this issue to workflow-cli instead.

**Comment by Joshua-Anderson** [comment] 2016-08-23 23:17
What field is used when deleting the key? It seems to me that `deis keys:remove jonathanchauncey@ENG000637.local` works.

**Comment by helgi** [comment] 2016-08-30 03:56
Going to mark this one as a duplicate of #1023 even if this is older

**Closed by helgi** 2016-08-30 03:56 UTC
Labels: bug
