### ISSUE TITLE
Controller registers new users despite disabled registration

### ISSUE THREAD

**Issue by oaojesse** [deis/controller#586] opened 2016-03-31 18:47 UTC
I have deis workflow up and running on GCE installed using helm following these instructions.
http://docs-v2.readthedocs.org/en/latest/installing-workflow/installing-deis-workflow/

I attempted to turn off user registration after registering my initial user by updating the `deis-controller` ReplicationController to include the environment variable `REGISTRATION_MODE=disabled` using `kubectl edit rc deis-controller --namespace=deis`. I then deleted the old pod, to get a new pod up with the environment variable.

Despite this the controller is still accepting new user registration.

    $ kubectl get pods --namespace=deis
    NAME                          READY     STATUS    RESTARTS   AGE 
    deis-builder-ghfx7            1/1       Running   2          3h
    deis-controller-cfh9p         1/1       Running   0          57m
    deis-database-iy25n           1/1       Running   0          3h
    deis-minio-lw5st              1/1       Running   0          3h
    deis-registry-758wn           1/1       Running   4          3h
    deis-router-knqdu             1/1       Running   0          3h
    deis-workflow-manager-b6b24   1/1       Running   0          3h

    $ kubectl exec deis-controller-cfh9p --namespace=deis env | grep REGISTRATION_MODE
    REGISTRATION_MODE=disabled

    $ deis register http://deis.my.domain
    username: newuser
    password:
    password (confirm):
    email: new@user.com
    Registered newuser
    Logged in as newuser

    $ deis whoami
    You are newuser at http://deis.my.domain

**Comment by bacongobbler** [comment] 2016-03-31 18:59
According to [this](https://github.com/deis/controller/blob/a5b704a2a1e73538fe7618d285032e2c9ca0a92a/rootfs/api/permissions.py#L97-L117) that should be the correct way to disable registration, as well as according to [this test case](https://github.com/deis/controller/blob/4cf1761836e950c712debab98d8688d55f27422c/rootfs/api/tests/test_auth.py#L66-L80). I'll see if I can reproduce this.

**Comment by bacongobbler** [comment] 2016-04-04 18:02
I can confirm this as well, following your instructions. `kd` is just an alias for `kubectl --namespace=deis` in this demo:

```
><> kd edit rc deis-controller
replicationcontroller "deis-controller" edited
><> kd delete po deis-controller-r2o1a
pod "deis-controller-r2o1a" deleted
><> kd exec deis-controller-0t6u8 env | grep REGISTRATION
REGISTRATION_MODE=disabled
><> deis register http://deis.$DEIS_TEST_DOMAIN --username test --password test --email test@example.com
Registered test
Logged in as test
```

Dropping into a python shell:

```
><> kd exec -it deis-controller-0t6u8 python manage.py shell
Python 3.5.1 (default, Dec  9 2015, 14:41:32) 
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from django.conf import settings 
>>> settings.REGISTRATION_MODE
'enabled'
```

**Comment by bacongobbler** [comment] 2016-04-04 18:11
Apparently this is something that was [not tunable for the beta](https://github.com/deis/controller/blob/v2.0.0-beta1/rootfs/deis/settings.py#L278-L279). This has since been fixed in master. @oaojesse can you confirm with the `workflow-dev` chart?

**Comment by oaojesse** [comment] 2016-04-05 16:03
Seems fixed in the `workflow-dev` chart. Thanks!

**Closed** 2016-04-05 16:03 UTC
