### ISSUE TITLE
annotation-based configuration?

### ISSUE THREAD

**Issue by JeanMertz** [deis/controller#839] opened 2016-06-25 08:15 UTC
The router component is easily configurable using annotations, it also correctly updates the nginx configuration when an annotation changes.

The controller requires setting environment variables, which requires manually editing the helm templates before deploying Deis (or, using `kubectl edit` and then deleting the relevant pods).

Could the controller also support annotations, for easier configuration?

**Comment by krancour** [comment] 2016-06-25 20:53
imo, it would be better if they (and all components) converged, eventually, on using ConfigMaps. That being said, the router is the odd man out in supporting dynamic re-configuration _while running_. That is quite by design. The router proxies traffic to all yours apps... you would not want to have to restart it every time you change the configuration, as that would lead to downtime for all your apps.

**Comment by helgi** [comment] 2016-09-29 01:17
If we move to ConfigMaps I'd suggest we use the file based version and https://github.com/gorakhargosh/watchdog or https://github.com/seb-m/pyinotify to detect changes, and running HUP on gunicorn... Or maybe not, could be sketchy

**Comment by bacongobbler** [comment] 2016-10-11 19:39
I'm going to close this based on the result of https://github.com/deis/router/pull/270, in which there isn't anything ConfigMaps are doing any better than our current workflow that would make us want to migrate.

**Closed by bacongobbler** 2016-10-11 19:39 UTC
Labels: enhancement
