### ISSUE TITLE
e2e failing: Deployment is already in progress

### ISSUE THREAD

**Issue by bacongobbler** [deis/controller#898] opened 2016-07-20 18:27 UTC
more testing for deis/charts#310:

```
$ deis auth:register http://deis.k8s.local --username=test-23570 --password=asdf1234 --email=test-23570@deis.io
Registered test-23570
Logged in as test-23570
$ deis apps:create test-469969636 --no-remote
Creating Application... done, created test-469969636
If you want to add a git remote for this app later, use `deis git:remote -a test-469969636`
$ deis config:set DEIS_KUBERNETES_DEPLOYMENTS=1 --app=test-469969636
Creating config... done

=== test-469969636 Config
DEIS_KUBERNETES_DEPLOYMENTS      1
$ deis builds:create --app=test-469969636 deis/example-dockerfile-http
Creating build... done
$ deis pull --app=test-469969636 deis/example-dockerfile-http
Creating build... Error: Unknown Error (400): map[detail:test-469969636-cmd (app::deploy): Deployment for test-469969636-cmd is already in progress]
$ deis apps:destroy --app=test-469969636 --confirm=test-469969636
Destroying test-469969636...
done in 6s
$ deis auth:cancel --username=test-23570 --password=asdf1234 --yes
Please log in again in order to cancel this account
Logged in as test-23570
Account cancelled


• Failure [183.310 seconds]
deis builds
/go/src/github.com/deis/workflow-e2e/tests/deployments_builds_test.go:151
  with an existing user
  /go/src/github.com/deis/workflow-e2e/tests/deployments_builds_test.go:149
    who owns an existing app that has already been deployed
    /go/src/github.com/deis/workflow-e2e/tests/deployments_builds_test.go:147
      that user can create a new build of that app from an existing image using `deis pull` [It]
      /go/src/github.com/deis/workflow-e2e/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:354

      No future change is possible.  Bailing out early after 19.454s.
      Expected
          <int>: 1
      to match exit code:
          <int>: 0

      /go/src/github.com/deis/workflow-e2e/tests/cmd/builds/commands.go:34
```

It doesn't seem like the controller is waiting long enough for the first deployment to finish before responding to the first `deis builds:create` request.

**Comment by bacongobbler** [comment] 2016-07-20 20:46
Other places where this occurs:

```
$ deis auth:register http://deis.k8s.local --username=test-81687 --password=asdf1234 --email=test-81687@deis.io
Registered test-81687
Logged in as test-81687
$ deis apps:create test-555296325 --no-remote
Creating Application... done, created test-555296325
If you want to add a git remote for this app later, use `deis git:remote -a test-555296325`
$ deis config:set DEIS_KUBERNETES_DEPLOYMENTS=1 --app=test-555296325
Creating config... done

=== test-555296325 Config
DEIS_KUBERNETES_DEPLOYMENTS      1
$ deis builds:create --app=test-555296325 deis/example-dockerfile-http
Creating build... done
$ deis healthchecks:set liveness tcpSocket -a test-555296325 80
Applying livenessProbe healthcheck... o..Error: Unknown Error (400): map[detail:test-555296325-cmd (app::deploy): Deployment for test-555296325-cmd is already in progress]
$ deis apps:destroy --app=test-555296325 --confirm=test-555296325
Destroying test-555296325...
done in 2s
$ deis auth:cancel --username=test-81687 --password=asdf1234 --yes
Please log in again in order to cancel this account
Logged in as test-81687
Account cancelled


• Failure [186.060 seconds]
deis healthchecks
/go/src/github.com/deis/workflow-e2e/tests/deployments_healthcheck_test.go:207
  with an existing user
  /go/src/github.com/deis/workflow-e2e/tests/deployments_healthcheck_test.go:173
    who owns an existing app that has already been deployed
    /go/src/github.com/deis/workflow-e2e/tests/deployments_healthcheck_test.go:172
      that user can set a tcpSocket liveness healthcheck [It]
      /go/src/github.com/deis/workflow-e2e/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:354

      No future change is possible.  Bailing out early after 19.617s.
      Got stuck at:
           o..
      Waiting for:
          === test-555296325 Healthchecks

      /go/src/github.com/deis/workflow-e2e/tests/deployments_healthcheck_test.go:90
```

**Comment by helgi** [comment] 2016-07-25 16:45
Was this observed locally or in e2e upstream?

**Comment by bacongobbler** [comment] 2016-07-25 16:47
observed locally

**Comment by helgi** [comment] 2016-07-25 16:50
Is it something you can reliably reproduce, and provide logs for? Wondering if you hit the timeout but it is not failing the first operation

**Comment by croemmich** [comment] 2016-08-12 15:28
I'm seeing this on our production cluster in 2.3.1. Will try to gather more info.

**Comment by helgi** [comment] 2016-08-12 15:34
Can you look at the status section of the Deployment object and see if all the replica counts match?

**Comment by croemmich** [comment] 2016-08-12 15:44
I'm guess they didn't. Unfortunately I already fixed it by scaling to 0, deploying, and scaling back up. If it happens again I'll post what I find. 

I don't know if it's related, but I've been having a few odd issue here and there seeming related stale pod info with config:set as well. A scale to 0 before running the set fixes that issue too.

**Comment by helgi** [comment] 2016-08-12 15:47
Yeah if you see it again then get the `status` of the Deployment and then look at the ReplicaSet / Pod associated and if they are having problems coming up.

If you can show me the `deis` output (the cli) as well from the command that triggered it then that'd be helpful as well

**Comment by croemmich** [comment] 2016-08-12 16:02
Here's the slightly sanitized command and controller log. Thanks for your help!

```
➜  myapp git:(master) git push deis master
Counting objects: 2544, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (1348/1348), done.
Writing objects: 100% (2544/2544), 1.30 MiB | 0 bytes/s, done.
Total 2544 (delta 1706), reused 1726 (delta 1107)
Starting build... but first, coffee!
Step 1 : FROM example/nginx-php7-laravel5:v1.25
# Executing 1 build trigger...
Step 1 : RUN /usr/local/bin/composer self-update
---> Using cache
---> 3641799bc0c6
Step 2 : MAINTAINER Chris Roemmich <croemmich@example.com>
---> Using cache
---> bafd609d22bf
Step 3 : ADD . /var/www/
---> Using cache
---> 8c3759f05e1d
Step 4 : COPY laravel-queue.conf /etc/supervisor/conf.d/laravel-queue.conf
---> Using cache
---> 36925878adcd
Step 5 : RUN composer install --no-dev
---> Using cache
---> a782230de750
Successfully built a782230de750
Pushing to registry
Build complete.
Launching App...
remote: 2016/08/12 15:18:34 Error running git receive hook [publishing release (Unexpected error occurred: Deployment for myapp-cmd is already in progress)]
To ssh://git@deis-builder.example.com:2222/myapp.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@deis-builder.example.com:2222/myapp.git'
```

```
ERROR:root:Deployment for myapp-cmd is already in progress
Traceback (most recent call last):
  File "/app/api/models/build.py", line 64, in create
    self.app.deploy(new_release)
  File "/app/api/models/app.py", line 544, in deploy
    raise AlreadyExists('Deployment for {} is already in progress'.format(name))
api.exceptions.AlreadyExists: Deployment for myapp-cmd is already in progress

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 474, in create
    super(BuildHookViewSet, self).create(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 21, in perform_create
    self.post_save(obj)
  File "/app/api/views.py", line 480, in post_save
    build.create(self.user)
  File "/app/api/models/build.py", line 71, in create
    raise DeisException(str(e)) from e
api.exceptions.DeisException: Deployment for myapp-cmd is already in progress
```

**Comment by helgi** [comment] 2016-08-12 16:05
Can you run `kubectl --namespace myapp get deployments myapp-cmd -o yaml` and show me the last ~5 lines (whatever is below `status`)

Also if you could drop a `kubectl --namespace myapp get po` for me

**Comment by croemmich** [comment] 2016-08-12 16:26
```
➜  ~ kubectl --namespace myapp  get deployments myapp-cmd -o yaml | tail -n 5
status:
  availableReplicas: 2
  observedGeneration: 13
  replicas: 2
  updatedReplicas: 2
```

```
➜  ~ kubectl --namespace myapp  get po                                  
NAME                               READY     STATUS    RESTARTS   AGE
myapp-cmd-681183878-j6zvi   1/1       Running   0          44m
myapp-cmd-681183878-uyqqu   1/1       Running   0          44m
```

**Comment by helgi** [comment] 2016-08-12 16:31
Hmmm that all looks fine! Currently all `in progress` checks verify is that `spec/replicas` matches up with `availableReplicas`, `replicas` and `updatedRepliacs` in `status`. 

If you try to deploy again does that still happen?

**Comment by croemmich** [comment] 2016-08-12 16:33
Let me make a change and give it a try. Before no matter how many times I pushed it continued to fail until I scaled to 0.

**Comment by helgi** [comment] 2016-08-12 16:38
Thanks - Any information is appreciated since I am working on something that will help with busting through "in progress" when the Deployment in fact failed or timed out. Usually happens when the client (or git) lose connection with the API tho and you don't seem to have any of the problems I'm solving for, which makes me very curious.

**Comment by croemmich** [comment] 2016-08-12 16:47
Just got this, which I believe is the same as what I occasionally get with config changes. Oddly, when I pushed again it worked.

```
➜  myapp git:(master) git push deis master
Counting objects: 1, done.
Writing objects: 100% (1/1), 204 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
Starting build... but first, coffee!
Step 1 : FROM example/nginx-php7-laravel5:v1.26
# Executing 1 build trigger...
Step 1 : RUN /usr/local/bin/composer self-update
---> Using cache
---> b19e0e57c608
Step 2 : MAINTAINER Chris Roemmich <croemmich@example.com>
---> Using cache
---> add10858030f
Step 3 : ADD . /var/www/
---> Using cache
---> b87fe45c3c36
Step 4 : COPY laravel-queue.conf /etc/supervisor/conf.d/laravel-queue.conf
---> Using cache
---> 2f4b6e5a5747
Step 5 : RUN composer install --no-dev
---> Using cache
---> cc79e495b408
Successfully built cc79e495b408
Pushing to registry
Build complete.
Launching App...
...
...
remote: 2016/08/12 16:42:00 Error running git receive hook [publishing release (Unexpected error occurred: ('failed to delete Pod "myapp-cmd-681183878-uyqqu" in Namespace "myapp": 404 Not Found\n{\'status\': \'Failure\', \'details\': {\'name\': \'myapp-cmd-681183878-uyqqu\', \'kind\': \'pods\'}, \'code\': 404, \'apiVersion\': \'v1\', \'metadata\': {}, \'reason\': \'NotFound\', \'kind\': \'Status\', \'message\': \'pods "myapp-cmd-681183878-uyqqu" not found\'}', 'myapp-cmd-681183878-uyqqu', 'myapp'))]
To ssh://git@deis-builder.example.com:2222/myapp.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@deis-builder.example.com:2222/myapp.git'
```

```
ERROR:root:('failed to delete Pod "myapp-cmd-681183878-uyqqu" in Namespace "myapp": 404 Not Found\n{\'status\': \'Failure\', \'details\': {\'name\': \'myapp-cmd-681183878-uyqqu\', \'kind\': \'pods\'}, \'code\': 404, \'apiVersion\': \'v1\', \'metadata\': {}, \'reason\': \'NotFound\', \'kind\': \'Status\', \'message\': \'pods "myapp-cmd-681183878-uyqqu" not found\'}', 'myapp-cmd-681183878-uyqqu', 'myapp')
Traceback (most recent call last):
  File "/app/api/models/build.py", line 64, in create
    self.app.deploy(new_release)
  File "/app/api/models/app.py", line 573, in deploy
    release.cleanup_old(deployments)
  File "/app/api/models/release.py", line 308, in cleanup_old
    self._scheduler.delete_pod(self.app.id, pod['metadata']['name'])
  File "/app/scheduler/__init__.py", line 1379, in delete_pod
    raise KubeHTTPException(resp, 'delete Pod "{}" in Namespace "{}"', name, namespace)
scheduler.KubeHTTPException: ('failed to delete Pod "myapp-cmd-681183878-uyqqu" in Namespace "myapp": 404 Not Found\n{\'status\': \'Failure\', \'details\': {\'name\': \'myapp-cmd-681183878-uyqqu\', \'kind\': \'pods\'}, \'code\': 404, \'apiVersion\': \'v1\', \'metadata\': {}, \'reason\': \'NotFound\', \'kind\': \'Status\', \'message\': \'pods "myapp-cmd-681183878-uyqqu" not found\'}', 'myapp-cmd-681183878-uyqqu', 'myapp')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 474, in create
    super(BuildHookViewSet, self).create(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 21, in perform_create
    self.post_save(obj)
  File "/app/api/views.py", line 480, in post_save
    build.create(self.user)
  File "/app/api/models/build.py", line 71, in create
    raise DeisException(str(e)) from e
api.exceptions.DeisException: ('failed to delete Pod "myapp-cmd-681183878-uyqqu" in Namespace "myapp": 404 Not Found\n{\'status\': \'Failure\', \'details\': {\'name\': \'myapp-cmd-681183878-uyqqu\', \'kind\': \'pods\'}, \'code\': 404, \'apiVersion\': \'v1\', \'metadata\': {}, \'reason\': \'NotFound\', \'kind\': \'Status\', \'message\': \'pods "myapp-cmd-681183878-uyqqu" not found\'}', 'myapp-cmd-681183878-uyqqu', 'myapp')
```

**Comment by helgi** [comment] 2016-08-12 16:51
oh... that's very random - Cleanup thinks it has pods to cleanup. I'll take a look at putting more guard rails on that code path

**Comment by helgi** [comment] 2016-08-30 01:16
2.4 should have fixed up a few things here. 2.4 (and 2.4.2 even more so) fixed this. Could you give 2.4.2 a go and see if you have better luck?

**Comment by helgi** [comment] 2016-08-30 21:57
@croemmich I'm going to close this ticket - feel free to reopen it if you still see this after 2.4.2, or open up a new ticket

**Closed by helgi** 2016-08-30 21:57 UTC
Labels: bug
