### ISSUE TITLE
invalid JSON saved to App model

### ISSUE THREAD

**Issue by mboersma** [deis/controller#441] opened 2016-03-01 18:45 UTC
It appears that an operation like `deis pull -p '{"web":1, "cron"1}'` proceeds without validating the JSON provided on the command line. This can cause a `JSONDecodeError` later that stops workflow from starting up properly--see #438.

**Comment by helgi** [comment] 2016-03-02 01:56
@aledbf do you know how you inserted that record? The YAML parser in the current CLI should catch things but I'm curious... I'm not able to reproduce things right now

**Comment by helgi** [comment] 2016-06-06 04:23
I'm going to close this on the count that this was affecting `structures` in the App model which is something only Django writes to. It is not the Procfile handling

**Closed by helgi** 2016-06-06 04:23 UTC
Labels: bug
