### ISSUE TITLE
Health check on startup logging improvments

### ISSUE THREAD

**Issue by sstarcher** [deis/controller#672] opened 2016-04-27 13:45 UTC
With deis-database and deis-registry down the controller goes into a crash loop, but it's logs don't reflect why.

```
system information:
Django Version: 1.9.5
Python 3.5.1
Django checks:
System check identified no issues (2 silenced).
Health Checks:
```

**Comment by bacongobbler** [comment] 2016-04-27 15:13
If the database is down, you should've at least seen "There was a problem connecting to the database" as seen [here](https://github.com/deis/controller/blob/master/rootfs/api/management/commands/healthchecks.py#L16). Is that not the case for you?

**Comment by sstarcher** [comment] 2016-04-27 15:34
@bacongobbler the database was certainly down, but that message was not logged.  The situation was that I attempted to launch everything without AWS credentials using a S3 bucket as the object store.

**Comment by helgi** [comment] 2016-04-27 15:45
Is that what you see when you do `kubectl logs --previous --namespace deis <controler-pod>`?

**Comment by kmala** [comment] 2016-04-27 16:11
@sstarcher can you do a `kubectl describe pod <controller-pod> --namespace=deis`
I got this error yesterday for sometime even when the database is up but wasn't able to reproduce it again. The describe pod showed me `Liveness probe failed: Get http://10.52.2.8:8000/healthz: dial tcp 10.52.2.8:8000: connection refused`

**Comment by sstarcher** [comment] 2016-04-27 16:25
@helgi yes, but my logs were pulled from our log shipper

@kmala what state would you like the cluster in?  The deis-database pod was in a crash loop.

If you guys want me to reproduce something you will have to special the specific situation.  This is a moving target as I uninstall and reinstall this setup every few mins tweaking the settings.

**Comment by kmala** [comment] 2016-04-27 16:32
I would like to know the output of the `kubectl describe pod <controller-pod> --namespace=deis` when the controller pod is restarting/crash loop and you don't see and logs because
it may be an issue with the liveness/readiness probe not able to complete the request as in my case where it makes sense there aren't any logs.

**Comment by helgi** [comment] 2016-04-27 16:34
@sstarcher I find it so weird nothing got returned since all we run is https://github.com/deis/controller/blob/master/rootfs/api/management/commands/healthchecks.py

You should have seen:
> There was a problem connecting to the database

And if DEBUG was turned on (if you are playing with things, might want to consider turning on DEBUG=1 in the RC for the controller, to catch more details about problems) then you would have even gotten the Exception, but somehow you got neither, hmm

**Comment by sstarcher** [comment] 2016-04-27 16:37
I'm uninstalling everything atm and I'll re-install with invalid S3 credentials to reproduce the crash loop for the 3 pods.  I'm currently installing workflow-dev.

**Comment by sstarcher** [comment] 2016-04-27 16:49
I re-deployed workflow-dev and removed S3 aws credentials. 

kubectl get pods --namespace=deis | grep -v Running
```
NAME                          READY     STATUS             RESTARTS   AGE
deis-controller-afecb         0/1       CrashLoopBackOff   5          8m
deis-database-wfm0n           0/1       CrashLoopBackOff   6          8m
deis-registry-r1jo9           0/1       CrashLoopBackOff   6          8m
```

 kubectl logs --previous --namespace deis deis-controller-afecb                                                                                                                     
```
system information:
Django Version: 1.9.5
Python 3.5.1
Django checks:
System check identified no issues (2 silenced).
Health Checks:
```

kubectl describe pod deis-controller-afecb --namespace=deis
```
Name:		deis-controller-afecb
Namespace:	deis
Node:		ip-10-0-40-214.ec2.internal/10.0.40.214
Start Time:	Wed, 27 Apr 2016 12:39:36 -0400
Labels:		app=deis-controller
Status:		Running
IP:		10.245.82.152
Controllers:	ReplicationController/deis-controller
Containers:
  deis-controller:
    Container ID:	docker://6688b0d20ceb0568c1c593db1934b748bd0507f33067ed4bd2c5c9525aeda878
    Image:		quay.io/deisci/controller:canary
    Image ID:		docker://114234d8454f6d7436cdf13d96f961162a3e90b68bcb126c27aef4a4c73c561d
    Port:		8000/TCP
    QoS Tier:
      cpu:		BestEffort
      memory:		BestEffort
    State:		Running
      Started:		Wed, 27 Apr 2016 12:45:47 -0400
    Last State:		Terminated
      Reason:		Error
      Exit Code:	137
      Started:		Wed, 27 Apr 2016 12:44:39 -0400
      Finished:		Wed, 27 Apr 2016 12:45:46 -0400
    Ready:		False
    Restart Count:	5
    Liveness:		http-get http://:8000/healthz delay=30s timeout=10s period=10s #success=1 #failure=3
    Readiness:		http-get http://:8000/healthz delay=30s timeout=10s period=10s #success=1 #failure=3
    Environment Variables:
      APP_STORAGE:		s3
      SLUGRUNNER_IMAGE_NAME:	quay.io/deisci/slugrunner:canary
      DEIS_SECRET_KEY:
      DEIS_BUILDER_KEY:
      DEIS_DATABASE_USER:
      DEIS_DATABASE_PASSWORD:
Conditions:
  Type		Status
  Ready 	False
Volumes:
  docker-socket:
    Type:	HostPath (bare host directory volume)
    Path:	/var/run/docker.sock
  django-secret-key:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	django-secret-key
  builder-key-auth:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	builder-key-auth
  database-creds:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	database-creds
  deis-controller-token-4ixzg:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	deis-controller-token-4ixzg
Events:
  FirstSeen	LastSeen	Count	From					SubobjectPath				Type		Reason			Message
  ---------	--------	-----	----					-------------				--------	------			-------
  6m		6m		1	{scheduler }											Scheduled		Successfully assigned deis-controller-afecb to ip-10-0-40-214.ec2.internal
  6m		6m		1	{kubelet ip-10-0-40-214.ec2.internal}	spec.containers{deis-controller}	Normal		Created			Created container with docker id 0c9cccfb9c6f
  6m		6m		1	{kubelet ip-10-0-40-214.ec2.internal}	spec.containers{deis-controller}	Normal		Started			Started container with docker id 0c9cccfb9c6f
  5m		5m		1	{kubelet ip-10-0-40-214.ec2.internal}	spec.containers{deis-controller}	Normal		Killing			Killing container with docker id 0c9cccfb9c6f: pod "deis-controller-afecb_deis(a0eee032-0c96-11e6-8045-0637dc2899a9)" container "deis-controller" is unhealthy, it will be killed and re-created.
  5m		5m		1	{kubelet ip-10-0-40-214.ec2.internal}	spec.containers{deis-controller}	Normal		Started			Started container with docker id cd35b3125d2e
  5m		5m		1	{kubelet ip-10-0-40-214.ec2.internal}	spec.containers{deis-controller}	Normal		Created			Created container with docker id cd35b3125d2e
  4m		4m		1	{kubelet ip-10-0-40-214.ec2.internal}	spec.containers{deis-controller}	Normal		Killing			Killing container with docker id cd35b3125d2e: pod "deis-controller-afecb_deis(a0eee032-0c96-11e6-8045-0637dc2899a9)" container "deis-controller" is unhealthy, it will be killed and re-created.
  4m		4m		1	{kubelet ip-10-0-40-214.ec2.internal}	spec.containers{deis-controller}	Normal		Started			Started container with docker id c31f6647c956
  4m		4m		1	{kubelet ip-10-0-40-214.ec2.internal}	spec.containers{deis-controller}	Normal		Created			Created container with docker id c31f6647c956
  3m		3m		1	{kubelet ip-10-0-40-214.ec2.internal}	spec.containers{deis-controller}	Normal		Killing			Killing container with docker id c31f6647c956: pod "deis-controller-afecb_deis(a0eee032-0c96-11e6-8045-0637dc2899a9)" container "deis-controller" is unhealthy, it will be killed and re-created.
  3m		3m		1	{kubelet ip-10-0-40-214.ec2.internal}	spec.containers{deis-controller}	Normal		Started			Started container with docker id 4ba76357bfe0
  3m		3m		1	{kubelet ip-10-0-40-214.ec2.internal}	spec.containers{deis-controller}	Normal		Created			Created container with docker id 4ba76357bfe0
  1m		1m		1	{kubelet ip-10-0-40-214.ec2.internal}	spec.containers{deis-controller}	Normal		Killing			Killing container with docker id 4ba76357bfe0: pod "deis-controller-afecb_deis(a0eee032-0c96-11e6-8045-0637dc2899a9)" container "deis-controller" is unhealthy, it will be killed and re-created.
  1m		1m		1	{kubelet ip-10-0-40-214.ec2.internal}	spec.containers{deis-controller}	Normal		Created			Created container with docker id b8f8dc7d0846
  1m		1m		1	{kubelet ip-10-0-40-214.ec2.internal}	spec.containers{deis-controller}	Normal		Started			Started container with docker id b8f8dc7d0846
  6m		1m		7	{kubelet ip-10-0-40-214.ec2.internal}	spec.containers{deis-controller}	Warning		Unhealthy		Liveness probe failed: Get http://10.245.82.152:8000/healthz: dial tcp 10.245.82.152:8000: connection refused
  6m		47s		6	{kubelet ip-10-0-40-214.ec2.internal}	spec.containers{deis-controller}	Normal		Pulling			pulling image "quay.io/deisci/controller:canary"
  6m		47s		22	{kubelet ip-10-0-40-214.ec2.internal}	spec.containers{deis-controller}	Warning		Unhealthy		Readiness probe failed: Get http://10.245.82.152:8000/healthz: dial tcp 10.245.82.152:8000: connection refused
  47s		47s		1	{kubelet ip-10-0-40-214.ec2.internal}	spec.containers{deis-controller}	Normal		Killing			Killing container with docker id b8f8dc7d0846: pod "deis-controller-afecb_deis(a0eee032-0c96-11e6-8045-0637dc2899a9)" container "deis-controller" is unhealthy, it will be killed and re-created.
  6m		46s		7	{kubelet ip-10-0-40-214.ec2.internal}						Warning		MissingClusterDNS	kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to DNSDefault policy.
  6m		46s		6	{kubelet ip-10-0-40-214.ec2.internal}	spec.containers{deis-controller}	Normal		Pulled			Successfully pulled image "quay.io/deisci/controller:canary"
  46s		46s		1	{kubelet ip-10-0-40-214.ec2.internal}	spec.containers{deis-controller}	Normal		Created			Created container with docker id 6688b0d20ceb
  46s		46s		1	{kubelet ip-10-0-40-214.ec2.internal}	spec.containers{deis-controller}	Normal		Started			Started container with docker id 6688b0d20ceb
```

**Comment by sstarcher** [comment] 2016-04-27 20:21
So my underlying issue is different than the previous one, but I'm seeing similar results.
My controller was running happily "I believe".  I deleted the controller and recreated it only changing a nodeSelector along with turning on DEBUG.  The controller is currently restarting over and over again.

```
+ echo system information:
++ ./manage.py --version
system information:
Django Version: 1.9.5
+ echo 'Django Version: 1.9.5'
+ python --version
Python 3.5.1
+ mkdir -p /app/data/logs
+ chmod -R 777 /app/data/logs
++ stat -c %g /var/run/docker.sock
+ addgroup -g 233 docker
+ addgroup deis docker
+ echo 'Django checks:'
+ python /app/manage.py check --deploy api
Django checks:
System check identified no issues (2 silenced).
+ echo 'Health Checks:'
+ python /app/manage.py healthchecks
Health Checks:
```

```
Name:		deis-controller-witik
Namespace:	deis
Node:		ip-10-0-30-184.ec2.internal/10.0.30.184
Start Time:	Wed, 27 Apr 2016 16:14:47 -0400
Labels:		app=deis-controller
Status:		Running
IP:		10.245.65.17
Controllers:	ReplicationController/deis-controller
Containers:
  deis-controller:
    Container ID:	docker://9654420e8c09dd129d2f409ca23ea146a8135f37ddd7042e8cb2ddcd79325712
    Image:		quay.io/deisci/controller:canary
    Image ID:		docker://114234d8454f6d7436cdf13d96f961162a3e90b68bcb126c27aef4a4c73c561d
    Port:		8000/TCP
    QoS Tier:
      memory:		BestEffort
      cpu:		BestEffort
    State:		Running
      Started:		Wed, 27 Apr 2016 16:20:38 -0400
    Last State:		Terminated
      Reason:		Error
      Exit Code:	137
      Started:		Wed, 27 Apr 2016 16:19:37 -0400
      Finished:		Wed, 27 Apr 2016 16:20:37 -0400
    Ready:		False
    Restart Count:	5
    Liveness:		http-get http://:8000/healthz delay=30s timeout=10s period=10s #success=1 #failure=3
    Readiness:		http-get http://:8000/healthz delay=30s timeout=10s period=10s #success=1 #failure=3
    Environment Variables:
      DEBUG:			1
      APP_STORAGE:		s3
      SLUGRUNNER_IMAGE_NAME:	quay.io/deisci/slugrunner:canary
      DEIS_SECRET_KEY:
      DEIS_BUILDER_KEY:
      DEIS_DATABASE_USER:
      DEIS_DATABASE_PASSWORD:
Conditions:
  Type		Status
  Ready 	False
Volumes:
  docker-socket:
    Type:	HostPath (bare host directory volume)
    Path:	/var/run/docker.sock
  django-secret-key:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	django-secret-key
  builder-key-auth:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	builder-key-auth
  database-creds:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	database-creds
  deis-controller-token-ks355:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	deis-controller-token-ks355
Events:
  FirstSeen	LastSeen	Count	From					SubobjectPath				Type		Reason			Message
  ---------	--------	-----	----					-------------				--------	------			-------
  6m		6m		1	{scheduler }											Scheduled		Successfully assigned deis-controller-witik to ip-10-0-30-184.ec2.internal
  6m		6m		1	{kubelet ip-10-0-30-184.ec2.internal}	spec.containers{deis-controller}	Normal		Created			Created container with docker id 6c8e15778b7d
  6m		6m		1	{kubelet ip-10-0-30-184.ec2.internal}	spec.containers{deis-controller}	Normal		Started			Started container with docker id 6c8e15778b7d
  5m		5m		1	{kubelet ip-10-0-30-184.ec2.internal}	spec.containers{deis-controller}	Normal		Killing			Killing container with docker id 6c8e15778b7d: pod "deis-controller-witik_deis(b05b4452-0cb4-11e6-b5b6-0637dc2899a9)" container "deis-controller" is unhealthy, it will be killed and re-created.
  5m		5m		1	{kubelet ip-10-0-30-184.ec2.internal}	spec.containers{deis-controller}	Normal		Started			Started container with docker id b4e52b29d659
  5m		5m		1	{kubelet ip-10-0-30-184.ec2.internal}	spec.containers{deis-controller}	Normal		Created			Created container with docker id b4e52b29d659
  3m		3m		1	{kubelet ip-10-0-30-184.ec2.internal}	spec.containers{deis-controller}	Normal		Killing			Killing container with docker id b4e52b29d659: pod "deis-controller-witik_deis(b05b4452-0cb4-11e6-b5b6-0637dc2899a9)" container "deis-controller" is unhealthy, it will be killed and re-created.
  3m		3m		1	{kubelet ip-10-0-30-184.ec2.internal}	spec.containers{deis-controller}	Normal		Created			Created container with docker id 3a196a420a27
  3m		3m		1	{kubelet ip-10-0-30-184.ec2.internal}	spec.containers{deis-controller}	Normal		Started			Started container with docker id 3a196a420a27
  2m		2m		1	{kubelet ip-10-0-30-184.ec2.internal}	spec.containers{deis-controller}	Normal		Created			Created container with docker id c46a41dccc30
  2m		2m		1	{kubelet ip-10-0-30-184.ec2.internal}	spec.containers{deis-controller}	Normal		Started			Started container with docker id c46a41dccc30
  2m		2m		1	{kubelet ip-10-0-30-184.ec2.internal}	spec.containers{deis-controller}	Normal		Killing			Killing container with docker id 3a196a420a27: pod "deis-controller-witik_deis(b05b4452-0cb4-11e6-b5b6-0637dc2899a9)" container "deis-controller" is unhealthy, it will be killed and re-created.
  1m		1m		1	{kubelet ip-10-0-30-184.ec2.internal}	spec.containers{deis-controller}	Normal		Created			Created container with docker id 67ecf13b8c8e
  1m		1m		1	{kubelet ip-10-0-30-184.ec2.internal}	spec.containers{deis-controller}	Normal		Killing			Killing container with docker id c46a41dccc30: pod "deis-controller-witik_deis(b05b4452-0cb4-11e6-b5b6-0637dc2899a9)" container "deis-controller" is unhealthy, it will be killed and re-created.
  1m		1m		1	{kubelet ip-10-0-30-184.ec2.internal}	spec.containers{deis-controller}	Normal		Started			Started container with docker id 67ecf13b8c8e
  5m		1m		7	{kubelet ip-10-0-30-184.ec2.internal}	spec.containers{deis-controller}	Warning		Unhealthy		Liveness probe failed: Get http://10.245.65.17:8000/healthz: dial tcp 10.245.65.17:8000: connection refused
  5m		42s		22	{kubelet ip-10-0-30-184.ec2.internal}	spec.containers{deis-controller}	Warning		Unhealthy		Readiness probe failed: Get http://10.245.65.17:8000/healthz: dial tcp 10.245.65.17:8000: connection refused
  6m		42s		6	{kubelet ip-10-0-30-184.ec2.internal}	spec.containers{deis-controller}	Normal		Pulled			Successfully pulled image "quay.io/deisci/controller:canary"
  6m		42s		6	{kubelet ip-10-0-30-184.ec2.internal}	spec.containers{deis-controller}	Normal		Pulling			pulling image "quay.io/deisci/controller:canary"
  6m		42s		7	{kubelet ip-10-0-30-184.ec2.internal}						Warning		MissingClusterDNS	kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to DNSDefault policy.
  42s		42s		1	{kubelet ip-10-0-30-184.ec2.internal}	spec.containers{deis-controller}	Normal		Killing			Killing container with docker id 67ecf13b8c8e: pod "deis-controller-witik_deis(b05b4452-0cb4-11e6-b5b6-0637dc2899a9)" container "deis-controller" is unhealthy, it will be killed and re-created.
  41s		41s		1	{kubelet ip-10-0-30-184.ec2.internal}	spec.containers{deis-controller}	Normal		Created			Created container with docker id 9654420e8c09
  41s		41s		1	{kubelet ip-10-0-30-184.ec2.internal}	spec.containers{deis-controller}	Normal		Started			Started container with docker id 9654420e8c09```

**Comment by sstarcher** [comment] 2016-04-27 20:23
It looks like this most recent error is what @kmala thought was happening in the original case.  So it looks like I have reproduced two different error paths.

**Comment by helgi** [comment] 2016-04-27 20:25
`connection refused` would suggest to me (without having proof) that k8s itself is being prevented by VPC / Firewall from hitting the controller endpoint, I might be wrong tho but it's pretty peculiar

**Comment by sstarcher** [comment] 2016-04-27 20:42
@helgi so the second error from https://github.com/deis/controller/issues/672#issuecomment-215215957

Was a problem in our K8S setup.  It was due to some nodes in the K8S cluster having different certs.  So part of the k8s proxy could talk to part of the cluster and the other k8s proxy could talk to the other part of the cluster.  It was fully a misconfiguration in our cluster and not Deis related.

**Comment by helgi** [comment] 2016-07-28 20:25
Is this still an issue? Have you observed this behaviour again?

Closing for now until we hear back

**Closed by helgi** 2016-07-28 20:25 UTC

**Comment by sstarcher** [comment] 2016-07-28 21:00
@helgi no clue it's been a long while and I'm not in the habit of mis configuring my system.
