### ISSUE TITLE
What should be the behavior of apps with different Proctypes in a Procfile?

### ISSUE THREAD

**Issue by kmala** [deis/controller#1094] opened 2016-09-29 19:54 UTC
These are few usecases and expected desired states i think should be.
### Install
1) No Procfile
use the default proctype present as part of the buildpacks.
2) Procfile present
deploy/scale the web type by default and others have to be manually done.
### Upgrade
1) No Procfile
same as install use the default proctype present as part of the buildpacks.
2) Procfile present
Use the current procfile and delete all the old proctypes including web if not present in the current one.

### Install
1) No Procfile
use the default proctype as cmd
2) Procfile present
if 'web' in the procfile use it or deploy 'cmd' as default
### Upgrade
1) No Procfile
same as install upgrade the default proctype cmd
2) Procfile present

- No procfile in the previous release: 
Use the current procfile and delete all the old proctypes not present in the current one except cmd .Delete the cmd if web is present in the procfile.
- procfile present the previous release:  
Use the current procfile and delete all the old proctypes not present in the current one except cmd and web.
i) If current procfile has web, delete the cmd if its present(means web is part of previous release).
ii) If current procfile doesn't have web, if previous release doesn't have web then continue with the cmd, if the previous release has web then remove web and create cmd.

Few use cases i mentioned above are not common but having a desired state will help.

**Comment by bacongobbler** [comment] 2016-09-29 20:59
Not sure what the ask is here. What is our scheduler's current state for these use cases? What issue are we trying to address here?

> procfile present the previous release:
> Use the current procfile and delete all the old proctypes not present in the current one except cmd and web. i) If current procfile has web, delete the cmd if its present(means web is part of previous release). ii) If current procfile doesn't have web, if previous release doesn't have web then continue with the cmd, if the previous release has web then remove web and create cmd.

So to clarify the upgrade process here:

 - v2 is deployed, pushed https://github.com/deis/example-dockerfile-procfile-http with one change: the Procfile defines a cmd, a timer and a worker process type
 - `deis scale cmd=3 worker=1 timer=1`
 - deploy v3, which is identical but the procfile has to changed from cmd to web, and timer is removed.

In this case, I should expect the following to happen:

1) the worker process is unchanged
2) the cmd and timer processes are scaled down to zero
3) no web process is deployed.

The reason behind this is documented in https://github.com/deis/deis/issues/2861. This is a pretty small edge case that shouldn't occur all that often and is pretty easy to document.

**Comment by bacongobbler** [comment] 2016-09-29 21:04
Also note this has been [documented](https://deis.com/docs/workflow/applications/managing-app-processes/#web-vs-cmd-process-types) since v1.6:

> If migrating an application from Heroku Buildpacks to a Docker-based deployment, Workflow will not automatically convert the web process type to cmd. To do this, you'll have to manually scale down the old process type and scale the new process type up.

**Comment by kmala** [comment] 2016-09-29 21:06
ok..then what should we do in this use case for a dockerfile deployment who has a procfile
> ii) If current procfile doesn't have web, if previous release doesn't have web then continue with the cmd, if the previous release has web then remove web and create cmd.

**Comment by bacongobbler** [comment] 2016-09-29 21:11
The user has to manually scale down the old process type and scale up the new one. It's less surprising to the user on upgrades. I think it's best that we keep least amount of surprises/edge cases during an upgrade as possible. Asking the user to scale down old processes and scale up new processes is fairly straightforward, IMO, and there is precedence for this as mentioned in deis/deis#2861.

**Comment by kmala** [comment] 2016-09-29 21:20
currently we are scaling down the old process type when removed from procfile even though if its web/cmd...this should be changed right?

**Comment by bacongobbler** [comment] 2016-09-29 21:33
I think there's a difference between how we recorded process types in v1 vs v2 now that the Container model no longer exists in the controller. I think that is okay, but it should be documented.

**Comment by helgi** [comment] 2016-09-29 21:53
Does any of this touch on https://github.com/deis/controller/issues/1062 ?

**Comment by kmala** [comment] 2016-09-29 21:54
yes, i am trying to find what we want as the actual behavior because changing procfiles can lead to undesired states during upgrades especially when the deploy fails.

**Comment by bacongobbler** [comment] 2016-09-29 22:00
In #1062 that is the intended behaviour. If you're using the `deis pull` workflow with a Procfile, you must always provide a Procfile either in your local directory or with `--procfile`. In other words, it's working as intended and we should document it if that isn't there already. That was a design decision we made.

**Comment by bacongobbler** [comment] 2016-10-11 19:53
closing so we can keep the discussion in #1062.

**Closed by bacongobbler** 2016-10-11 19:53 UTC
